forge_support: true
connection_throttle_limit: 3
timeout: 30000
online_mode: true
log_commands: false
listeners:
- query_port: 25566
  motd: Want to play a game?
  tab_list: GLOBAL_PING
  query_enabled: true
  proxy_protocol: false
  forced_hosts:
    portal.iocraft.org: United_States
    play.iocraft.org: United_States
    us.iocraft.org: United_States
    turkey.iocraft.org: Turkey
    canada.iocraft.org: Canada
  ping_passthrough: true
  priorities:
  - United_States
  - Turkey
  - Canada
  bind_local_address: true
  host: 0.0.0.0:25565
  max_players: 90
  tab_size: 90
  force_default_server: false
connection_throttle: 4000
groups:
  md_5:
  - admin
log_pings: true
ip_forward: true
prevent_proxy_connections: false
network_compression_threshold: 256
disabled_commands:
- disabledcommandhere
stats: a9ac05cb-05fd-4989-b176-b0e439f019fd
permissions:
  default:
  - bungeecord.command.server
  - bungeecord.command.list
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
servers:
  United_States:
    motd: Want to play a game?
    address: us-backend.iocraft.org:25565
    restricted: false
  Turkey:
    motd: Want to play a game?
    address: turkey-backend.iocraft.org:25565
    restricted: false
  Canada:
    motd: Want to play a game?
    address: canada-backend.iocraft.org:25565
    restricted: false
player_limit: -1
